import json
from dataclasses import replace

import numpy as np
import pytest

from apexsim.research.continuous_reference import tiny_continuous_reference
from apexsim.research.fienia_strategy import PaperStrategyModel, PaperStrategyParameters, TireWearCoefficients
from apexsim.research.strategy_solver import (
    EnumeratedStrategySolver,
    FixedPlanProblem,
    SolverAbstention,
    SolverSettings,
    energy_starts,
)
from apexsim.sim_core.types import TyreCompound

pytest.importorskip("casadi", reason="CI installs the required optimization extra")
DRY = (TyreCompound.SOFT, TyreCompound.MEDIUM, TyreCompound.HARD)
PLAN = (None, TyreCompound.SOFT, None)


def tiny_model(linear=False):
    p = PaperStrategyParameters(total_laps=3, initial_fuel_kg=6, battery_capacity_mj=1,
                                battery_delta_min_mj=-1, battery_delta_max_mj=.5)
    if linear:
        p = replace(p, battery_deploy_time_s_per_mj=.4, battery_recharge_time_s_per_mj=.4)
    return PaperStrategyModel(p, wear_coefficients={c: TireWearCoefficients(1., 0., .01) for c in DRY})


@pytest.mark.parametrize("linear", [False, True])
def test_solver_recovers_independent_continuous_vertex_optimum(linear):
    model = tiny_model(linear)
    reference = tiny_continuous_reference(model, pit_window=(1, 1))
    result = EnumeratedStrategySolver(model).solve(pit_window=(1, 1))
    assert result.solution.smooth_race_time_s == pytest.approx(reference.race_time_s, abs=1e-6, rel=0)
    assert result.report["all_plans_have_accepted_solution"]
    assert result.report["accepted_attempts"] > 0
    assert not result.report["global_optimality_certified"]
    assert result.report["plans"] == 2
    assert abs(result.solution.terminal_fuel_mj) <= 1e-7
    assert abs(result.solution.terminal_battery_mj) <= 1e-7
    assert result.solution.max_primal_violation <= 1e-7
    ratios = [a.fuel_energy_mj/model.p.nominal_fuel_energy_mj() for a in result.solution.actions]
    np.testing.assert_allclose(ratios, [1.1, 1., .9], atol=1e-5, rtol=0)
    if linear:
        # Independently hand calculated, not generated by the graph/reference code.
        assert reference.race_time_s == pytest.approx(305.626825, abs=1e-10, rel=0)


def test_scalar_replay_and_full_problem_derivatives_match_casadi():
    problem = FixedPlanProblem(tiny_model(), PLAN)
    for start in energy_starts(problem.model):
        solution = problem.replay(start)
        assert solution.max_legacy_action_adjustment_mj < 1e-10
        assert abs(solution.smooth_race_time_s-solution.original_race_time_s) <= 3*problem.map.approximation_bound_s
        gradient, jacobian = np.asarray(problem.gradient(start)).reshape(-1), np.asarray(problem.jacobian(start))
        for i in range(len(start)):
            offset = np.eye(len(start))[i]*1e-5
            fd = (float(problem.objective(start+offset))-float(problem.objective(start-offset)))/2e-5
            assert gradient[i] == pytest.approx(fd, abs=1e-6, rel=1e-5)
            fd_g = np.asarray(problem.constraints(start+offset)-problem.constraints(start-offset)).reshape(-1)/2e-5
            np.testing.assert_allclose(jacobian[:, i], fd_g, atol=1e-8, rtol=1e-5)


def test_mass_coupled_wear_is_feasible_but_cannot_claim_tiny_certificate():
    model = PaperStrategyModel(PaperStrategyParameters(total_laps=6, initial_fuel_kg=12,
                                                      battery_capacity_mj=2, battery_delta_min_mj=-1))
    result = EnumeratedStrategySolver(model).solve(pit_window=(2, 2))
    assert result.solution.max_primal_violation <= 1e-7
    assert not result.report["global_optimality_certified"]
    assert all(0 <= s.tyre_wear <= 1.25 for s in result.solution.states)
    with pytest.raises(ValueError, match="mass-independent"):
        tiny_continuous_reference(model)


def test_successful_but_worse_local_solve_keeps_checked_feasible_incumbent(monkeypatch):
    model = tiny_model()
    class Backend:
        def __init__(self, problem):
            self.problem = problem
        def __call__(self, **kwargs):
            x = energy_starts(model)[0]
            return {"x": x, "f": float(self.problem.objective(x))}
        def stats(self):
            return {"success": True, "return_status": "fixture_success", "iter_count": 1}
    monkeypatch.setattr(FixedPlanProblem, "backend", lambda self, settings: Backend(self))
    result = EnumeratedStrategySolver(model).solve(pit_window=(1, 1))
    assert result.solution.smooth_race_time_s == pytest.approx(
        tiny_continuous_reference(model, pit_window=(1, 1)).race_time_s, abs=1e-10, rel=0)
    assert result.report["attempts"][result.report["selected_attempt"]]["selected_source"] == "feasible_start"
    assert not result.report["global_optimality_certified"]


@pytest.mark.parametrize("values", [[1, 2], [1]*5+[float("nan")], [1]*5+[float("inf")],
                                   [1, 1, 1, 0, 0, 0], [1.2, .9, .9, -.5, 0, -.5],
                                   [1, 1, .95, -.5, 0, -.5], [1, 1, 1, .5, -1, -.5],
                                   [1e308, 1, 1, -.5, 0, -.5]])
def test_bad_or_infeasible_controls_are_rejected(values):
    with pytest.raises(ValueError):
        FixedPlanProblem(tiny_model(), PLAN).replay(values)


@pytest.mark.parametrize("plan", [(None,), (None, None, TyreCompound.SOFT),
                                 (None, TyreCompound.WET, None), (None, None, None)])
def test_unsupported_or_illegal_fixed_plan_fails(plan):
    with pytest.raises(ValueError):
        FixedPlanProblem(tiny_model(), plan)


def test_consecutive_pits_reset_wear_and_match_legacy_modes_and_states():
    problem = FixedPlanProblem(tiny_model(True), (TyreCompound.SOFT, TyreCompound.HARD, None))
    result = problem.replay(energy_starts(problem.model)[0])
    assert [s.compound for s in result.states] == [TyreCompound.MEDIUM, TyreCompound.SOFT,
                                                 TyreCompound.HARD, TyreCompound.HARD]
    assert [s.outlap for s in result.states] == [False, True, True, False]
    assert result.states[1].tyre_wear == result.states[2].tyre_wear == 0
    assert max(result.legacy_state_errors.values()) < 1e-10
    assert result.smooth_race_time_s == pytest.approx(result.original_race_time_s, abs=1e-10, rel=0)


def test_budget_and_window_rejections_happen_before_any_solver(monkeypatch):
    def unexpected(*args, **kwargs):
        pytest.fail("Budget failures must not construct a solver")
    monkeypatch.setattr(FixedPlanProblem, "backend", unexpected)
    with pytest.raises(ValueError, match="no partial"):
        EnumeratedStrategySolver(tiny_model(), SolverSettings(max_pit_sequences=1)).solve()
    with pytest.raises(ValueError, match="max_laps"):
        EnumeratedStrategySolver(PaperStrategyModel(PaperStrategyParameters(total_laps=9))).solve()
    with pytest.raises(ValueError, match="final lap"):
        EnumeratedStrategySolver(tiny_model()).solve(pit_window=(2, 2))


@pytest.mark.parametrize("success,corrupt", [(False, False), (True, True), (True, False)])
def test_bad_backend_status_or_infeasible_output_abstains(monkeypatch, success, corrupt):
    class Backend:
        def __call__(self, **kwargs):
            x = kwargs["x0"].copy()
            if corrupt:
                x[-1] = 1
            return {"x": x, "f": float("nan")}
        def stats(self):
            return {"success": success, "return_status": "fixture_status", "iter_count": 1}
    monkeypatch.setattr(FixedPlanProblem, "backend", lambda *args: Backend())
    with pytest.raises(SolverAbstention) as error:
        EnumeratedStrategySolver(tiny_model()).solve(pit_window=(1, 1))
    assert error.value.report["accepted_attempts"] == 0
    assert len(error.value.report["attempts"]) == 6
    assert all(not a["accepted"] and a["reason"] for a in error.value.report["attempts"])


def test_plugin_failure_and_empty_legal_schedule_abstain_with_diagnostics(monkeypatch):
    def missing(*args):
        raise RuntimeError("fixture: IPOPT plugin unavailable")
    monkeypatch.setattr(FixedPlanProblem, "backend", missing)
    with pytest.raises(SolverAbstention) as error:
        EnumeratedStrategySolver(tiny_model()).solve(pit_window=(1, 1))
    assert all(a["stage"] == "plugin_creation" for a in error.value.report["attempts"])
    with pytest.raises(SolverAbstention) as error:
        EnumeratedStrategySolver(tiny_model()).solve(pit_window=(0, -1))
    assert error.value.report["plans"] == 0


def test_infeasible_unclipped_wear_abstains_instead_of_repairing():
    model = tiny_model()
    model.wear = {c:TireWearCoefficients(1., 0., 5.) for c in DRY}
    with pytest.raises(SolverAbstention) as error:
        EnumeratedStrategySolver(model, SolverSettings(max_iterations=80)).solve(pit_window=(1, 1))
    assert not error.value.report["all_plans_have_accepted_solution"]


@pytest.mark.parametrize("kwargs", [{"max_laps":9}, {"max_pit_sequences":True}, {"max_iterations":0},
                                    {"solver_tolerance":float("nan")}, {"primal_tolerance":1.}])
def test_bad_solver_settings_fail(kwargs):
    with pytest.raises(ValueError):
        SolverSettings(**kwargs)


def test_reference_refuses_nonconcave_family_and_uses_no_solver(monkeypatch):
    model = tiny_model()
    model.p = replace(model.p, battery_recharge_time_s_per_mj=.8)
    with pytest.raises(ValueError, match="concave"):
        tiny_continuous_reference(model)
    def unexpected(*args, **kwargs):
        pytest.fail("Independent reference must not access solver helpers")
    monkeypatch.setattr(FixedPlanProblem, "__init__", unexpected)
    result = tiny_continuous_reference(tiny_model(True), pit_window=(1, 1))
    assert result.race_time_s == pytest.approx(305.626825, abs=1e-10, rel=0)


def test_solver_cli_artifact_inventory_seals_and_exclusive_output(tmp_path):
    from typer.testing import CliRunner

    from apexsim.cli import app
    from apexsim.provenance import file_sha256, payload_sha256

    output = tmp_path / "acceptance"
    result = CliRunner().invoke(app, ["strategy-solver-demo", "--output", str(output)])
    assert result.exit_code == 0, result.output
    summary = json.loads(result.output)
    assert summary["passed"] and summary["reference_cases"] == 2 and summary["max_absolute_regret_s"] < 1e-6
    assert summary["maturity"] == "R0" and not summary["global_solver_optimality_certified"]
    for name in ("summary", "manifest"):
        sealed = json.loads((output / f"{name}.json").read_text())
        digest = sealed.pop("content_sha256")
        assert payload_sha256(sealed) == digest
    manifest = json.loads((output / "manifest.json").read_text())
    assert set(manifest["files"]) == {"cases.json", "summary.json"}
    assert set(p.name for p in output.iterdir()) == {*manifest["files"], "manifest.json"}
    for name, info in manifest["files"].items():
        assert info == {"sha256": file_sha256(output/name), "bytes": (output/name).stat().st_size}
    cases = json.loads((output / "cases.json").read_text())
    assert len(cases) == 3 and cases[-1]["reference"] is None and cases[-1]["regret_s"] is None
    before = {p.name: p.read_bytes() for p in output.iterdir()}
    result = CliRunner().invoke(app, ["strategy-solver-demo", "--output", str(output)])
    assert isinstance(result.exception, FileExistsError)
    assert before == {p.name: p.read_bytes() for p in output.iterdir()}


def test_failed_solver_acceptance_creates_no_artifacts(tmp_path, monkeypatch):
    from apexsim.examples import strategy_solver_demo

    original = strategy_solver_demo.tiny_continuous_reference
    def wrong(*args, **kwargs):
        result = original(*args, **kwargs)
        return replace(result, race_time_s=result.race_time_s - 1)
    monkeypatch.setattr(strategy_solver_demo, "tiny_continuous_reference", wrong)
    output = tmp_path / "failed"
    with pytest.raises(ValueError, match="missed the independent tiny optimum"):
        strategy_solver_demo.run_strategy_solver_demo(output)
    assert not output.exists()
